# html lang
# ---------------
language: en

# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:


# navigation menu
menu: 
  - name: Archives
    slug: archives
    url: /archives  
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

node_sass:  
  outputStyle: compressed

# Article

# Open toc 
toc: true
# Open share 
share: true

# jsonContent:
#   searchLocal: true
#   searchGoogle: false
#   posts:
#     title: true
#     text: true
#     description: true
#     content: true
#     categories: false
#     tags: false

# use url, not username
social:
- slug: github
  url: https://github.com/ejazhussain
- slug: twitter
  url: https://twitter.com/EjazHussain_
- slug: rss
	url: /atom.xml






 