# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
brand: EJAZHUSSAIN
title: Ejaz Hussain
subtitle: ""
description: "I am a senior sharepoint developer focused on SharePoint, Office 365, PowerShell and Azure Technologies."
keywords:
  - Azure
  - Office 365
  - SharePoint Online
  - PowerShell  
author: Ejaz Hussain
avatar: /images/avatar.jpg
favicon: /images/favicon.ico
language: en
timezone: Europe/London

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://localhost:4000/ #https://www.ejazhussain.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

#Anlaytics
google_analytics: UA-69679122-1


# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

disqus_shortname: ejazhussain
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ejazhussain
search:
  path: search.xml
  field: post

autoprefixer:
  exclude:
    - '*.min.css'
  # remove: false # prevent autoprefixer remove page-break-inside
  # browsers:
  #   - 'last 2 versions'
  #   - '> 5%'

# Generator json content
jsonContent:
  meta: true
  title: true
  subtitle: true
  description: true
  author: true
  url: true
  keywords: true # (english, spanish, polish, german, french, italian, dutch, russian, portuguese, swedish)
  pages:
    title: true
    slug: false
    date: false
    updated: false
    comments: false
    path: true
    link: false
    permalink: true
    excerpt: false
    keywords: false
    text: false
    raw: false
    content: true
  posts:
    title: true
    slug: false
    date: false
    updated: false
    comments: false
    path: true
    link: false
    permalink: true
    excerpt: false
    keywords: true
    text: false
    raw: false
    content: true
    categories: false
    tags: false
  

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
# Deployment
## Docs: https://hexo.io/docs/deployment.html

browsersync:
  logLevel: "warn"
  ghostMode:
    scroll: true
  instanceName: "uniqueString"


prism_plugin:
  mode: 'realtime'    # realtime/preprocess
  theme: 'coy'
  line_number: true    # default false
  #custom_css: 'path/to/your/custom.css'     # optional

# add caption for iamges
image_caption:
  enable: true #false to disable
  class_name: #if you wanna customize the style for the caption,you can assign a class name, default is 'image-caption'